-----------------------------------------
-- 5. CASO PRACTICO
-----------------------------------------

-- ANALISIS EXPLORATORIO
CREATE OR REPLACE VIEW BENEF_MARGE_REG AS
SELECT
    A.REGION,
    ROUND(SUM(S.PROFIT), 2)             AS TOTAL_BENEFICIO,
    ROUND(MIN(S.PROFIT), 2)             AS BENEFICIO_MINIMO,
    ROUND(MAX(S.PROFIT), 2)             AS BENEFICIO_MAXIMO,
    ROUND(AVG(S.PROFIT), 2)             AS BENEFICIO_PROMEDIO,
    ROUND(STDDEV(S.PROFIT), 2)          AS DESVIACION_BENEFICIO,
    ROUND(AVG(CASE 
                  WHEN S.TOTAL = 0 THEN NULL 
                  ELSE (S.PROFIT / S.TOTAL) * 100 
              END), 2)                  AS PROMEDIO_MARGEN_PORC
FROM SALES S 	JOIN ACCOUNTS A	    
ON S.ACCOUNT = A.ACCOUNT
GROUP BY A.REGION
ORDER BY TOTAL_BENEFICIO DESC;

SELECT * FROM BENEF_MARGE_REG;

SELECT 
    A.REGION,
    A.INDUSTRY,
    ROUND(SUM(S.PROFIT), 2)         AS TOTAL_BENEFICIO,
    CASE 
        WHEN SUM(S.TOTAL) = 0 THEN NULL
        ELSE ROUND(SUM(S.PROFIT) / SUM(S.TOTAL) * 100, 2)
    END AS MARGEN_PORC,
    CASE
        WHEN SUM(S.TOTAL) = 0 THEN 'Sin datos'
        WHEN ROUND(SUM(S.PROFIT) / SUM(S.TOTAL) * 100, 2) > 38 THEN 'Alto'
        WHEN ROUND(SUM(S.PROFIT) / SUM(S.TOTAL) * 100, 2) BETWEEN 33 AND 38 THEN 'Medio'
        ELSE 'Bajo'
    END AS RENDIMIENTO
FROM SALES S
JOIN ACCOUNTS A         ON S.ACCOUNT = A.ACCOUNT
GROUP BY A.REGION, A.INDUSTRY
ORDER BY REGION DESC, MARGEN_PORC DESC;

